//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecSpares.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\CJT\\\\OneDrive\\\\Documents\\\\RecSpares\\\\RecSpares.xlsx")]
        public string JobFilePath {
            get {
                return ((string)(this["JobFilePath"]));
            }
            set {
                this["JobFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\CJT\\\\OneDrive\\\\Documents\\\\RecSpares\\\\RecSpares.xlsx")]
        public string MasterFilePath {
            get {
                return ((string)(this["MasterFilePath"]));
            }
            set {
                this["MasterFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\CJT\\\\OneDrive\\\\Documents\\\\RecSpares\\\\RecSpares.xlsx")]
        public string AllJobsFilePath {
            get {
                return ((string)(this["AllJobsFilePath"]));
            }
            set {
                this["AllJobsFilePath"] = value;
            }
        }
    }
}
